POST https://docsign.se/api/parties
Content-Type: application/json

{
    "api_key": "{{$apiKey}}",
    "name":"Albin Daleby",
    "email":"albin.daleby@sprinto.se",
    "phone_number":"0",
    "sign_method":"bankid"
}